#!/usr/bin/python3


import sys
import pprint
from os.path import exists, basename

# Add backticks to path
# sys.path.append("../")

from backticks import BT_to_C


py_file_name = sys.argv[0]
bt_file_path = sys.argv[1]
args = sys.argv[2:]

source = BT_to_C(bt_file_path)

if len(args):
    dpcf = False
    if args.count("--dpcf"):
        dpcf = True

    if args.count("build"):
        source.check_and_compile(dpcf)

    if args.count("run"):
        source.run()


# print("GLOBALS\n")
# pprint.pprint(source._vars_dict["GLOBALS"]["global_vars"])
# print("\n\n")
# print("FUNCS\n")
# pprint.pprint(source._vars_dict["FUNCS"])
# print("\n\n")
# print("CLASSES\n")
# pprint.pprint(source._class_vars_dict)


# pprint.pprint(source.tokens)
# pprint.pprint(source._imports_dict)
# print(source._imports_dict)
