#!/usr/bin/python3


import sys
import pprint
# Add backticks to path
# sys.path.append("../")
from backticks import BT_to_C


py_file_name = sys.argv[0]
bt_file_path = sys.argv[1]


# while bt_file_name.find("/"):
args = sys.argv[2:]


source = BT_to_C(bt_file_path)
if len(args):
    if args.count("build"):
        if args.count("del_c"):
            source.compile("gcc", True)
        else:
            source.compile("gcc", False)

    if args.count("run"):
        source.run()


# print("GLOBALS\n")
# pprint.pprint(source._vars_dict["GLOBALS"]["global_vars"])
# print("\n\n")
# print("FUNCS\n")
# pprint.pprint(source._vars_dict["FUNCS"])
# print("\n\n")

print("CLASSES\n")
pprint.pprint(source._vars_dict["CLASSES"])
print("\n\n")

# pprint.pprint(source.tokens)
# pprint.pprint(source._imports_dict)
# print(source._imports_dict)
