#!/usr/bin/python3


import sys
# Add backticks to path
sys.path.append("../")
from backticks import BT_to_C


py_file_name = sys.argv[0]
bt_file_name = sys.argv[1]


# while bt_file_name.find("/"):
args = sys.argv[2:]

source = BT_to_C(bt_file_name)

# print(source.tokens)

source.compile("gcc")
source.run()